### PR TITLE
Fix for #1826 ApplyInfix parentheses syntax

### LINKED ISSUE #1826: ApplyInfix syntax removes needed parentheses in Tuple and Placeholder
As discussed in #1817. 

Pretty printing syntax on both `Term.Select(Term.Placeholder, _)` and `Term.Tuple` remove parentheses which are needed.

I'm working on a fix ATM.

### PR DESCRIPTION
**Pull request by hugo-vrijswijk**
Fixes #1826 syntax printer bugs.

~One case still fails: `list map (_ diff foo)`. It adds an extra set of parentheses around the argument. I am unsure why that fails but another case `list map (_ -> foo)` does work, as they seem to have the same AST.~

### CODE REVIEW

File: scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala [hunk 1]
```diff
@@ -292,8 +292,8 @@ object TreeSyntax {
                     case _ => false
                   } =>
                   true
-                // Include parentheses for `a op (bar: _*)`
-                case repeated: Term.Repeated =>
+                // Include parentheses for `a op (b: _*)`, tuple `a op ((b, c))`, `a op (_.bar), a op (_.opTwo(b))`, `a op (_ opTwo b)`
+                case _: Term.Repeated | _: Term.Tuple |  Term.Select(_: Term.Placeholder, _) | Term.Apply(Term.Select(_: Term.Placeholder, _), _) | Term.ApplyInfix(_: Term.Placeholder, _, _, _) =>
```
Comment (olafurpg) [inline scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala]: Would it make sense to flip the logic around and not introduce parentheses for a whitelist of trees? Maybe it's enough to only skip parentheses for `_: Term.Ref`

Comment (hugo-vrijswijk) [reply scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala]: Hmm, good idea. I'll try it

**Comment by olafurpg** [comment]
Please ping me when this is ready for a review.

File: scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala (hunk 1 above)
Comment (hugo-vrijswijk) [reply scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala]: Ok, so I've (mostly) flipped it around. It's a little cleaner and should err on the side of adding parentheses in most cases. However, there's still some weird behaviour:

`list map (_ -> foo)` -> ` list map (_ -> foo)`
`list map (_ op foo)` -> ` list map ((_ op foo))` (Note the double parentheses)

I have no idea where this comes from, as far as I can tell [the AST's are the same](https://astexplorer.net/#/gist/38a1965132e6d507f974bd345c71caf1/df1fc34cbaa19b2c87e2087fd2856af24f141c62).

**Comment by hugo-vrijswijk** [comment]
@olafurpg It's ready now. Have a look at my comment

File: scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala (hunk 1 above)
Comment (olafurpg) [reply scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala]: Those parentheses could be caused by the pretty-printer for `Term.ApplyInfix`

Comment (hugo-vrijswijk) [reply scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala]: Isn't `_ -> foo` also a `Term.ApplyInfix` though? It seems to work there. With some testing it looks to me like the difference comes from using symbols or not

File: tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala [hunk 2]
```diff
@@ -660,4 +660,28 @@ class SyntacticSuite extends scala.meta.tests.parsers.ParseSuite {
     assert(q"list map (add(_, 1))".syntax == "list map (add(_, 1))")
     assert(q"list map (bar:_*)".syntax == "list map (bar: _*)")
   }
+  test("#1826 ApplyInfix parentheses on Select") {
+    assert(q"list map (_.bar)".syntax == "list map (_.bar)")
```
Comment (olafurpg) [inline tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala]: Can we introduce a helper method to run those assertions and verify the AST is unchanged?
```
def check(original: Tree, expected: String): Unit = {
  assertNoDiff(original.syntax == expected)
  assertNoDiff(original.structure = parseStat(expected).structure)
}
```

File: scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala [hunk 3]
```diff
@@ -286,17 +286,20 @@ object TreeSyntax {
...
+                case Term.Select(_: Term.Placeholder, _) => // `a op (_.b)`
                   true
-                // Include parentheses for `a op (bar: _*)`
-                case repeated: Term.Repeated =>
+                case Term.Apply(Term.Select(lhs: Term.Placeholder, _), _) => // `a op (_.b(c))`
                   true
-                case _ =>
+                case Term.ApplyInfix(lhs, _, _, _) if !lhs.isInstanceOf[Term.Placeholder] => // Not `a op (_ b c)`
+                  false
+                case _: Lit | _: Term.Ref | _: Term.Function | _: Term.Apply | _: Term.If | _: Term.Match =>
```
Comment (olafurpg) [inline scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala]: Is `Term.Match` correct here?
```scala
scala> List(1) map _ match { case 1 => println("BOOM") }
<console>:12: error: missing parameter type for expanded function
The argument types of an anonymous function must be fully known. (SLS 8.5)
Expected type was: ?
       List(1) map _ match { case 1 => println("BOOM") }
                   ^

scala> List(1) map (_ match { case 1 => println("BOOM") })
BOOM
res1: List[Unit] = List(())
```

Comment (hugo-vrijswijk) [reply scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala]: I am not entirely sure, but it seems to want to add double parentheses without it. I've added a test for that case though (and there were some others)

File: tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala (hunk 2 above)
Comment (hugo-vrijswijk) [reply tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala]: Done

**Comment by olafurpg** [comment]
There seems to be a failing test case
```
- #1826 ApplyInfix parentheses on ApplyInfix function *** FAILED ***
[info]   "list map ([(_ diff foo)])" did not equal "list map ([_ diff foo])" (SyntacticSuite.scala:692)
[info]   Analysis:
[info]   "list map ([(_ diff foo)])" -> "list map ([_ diff foo])"
```

**Comment by hugo-vrijswijk** [comment]
Yeah, I can't see why it fails though. It adds two parentheses on this case, but only one on a test with the same structure but different operator (`list map (_ -> foo)`)

File: scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala (hunk 1 above)
Comment (olafurpg) [reply scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala]: It depends on how the pretty-printer interprets those trees, they can be printed differently even if the AST is identical. The code quality is quite bad in the pretty-printer, it was written before my time and I haven't touched it much.

**Comment by RCMartins** [comment]
If you change line 304 from
`if (needsParens) s("(", p(InfixExpr(t.op.value), arg, right = true), ")")`
to
`if (needsParens) s("(", arg, ")")`
 it makes the `list map (_ diff foo)` test pass

The problem here is operator precedence. the `p` function checks if the parens are required based on the operators precedence. Because we already know it needs parens (and we don't want multiple) we should skip the call to `p`.

> Yeah, I can't see why it fails though. It adds two parentheses on this case, but only one on a test with the same structure but different operator (`list map (_ -> foo)`)

In the `list map (_ -> foo)` test `p` doesn't put parens because the operator `->` has greater precedence than `map`, you can see the precedence list it uses here: https://github.com/scalameta/scalameta/blob/232d56a457f92582ca2cc1ac5a8f96780a8415f4/scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/package.scala#L41

---

But the next test in the same block: `list map (a diff foo)  --->  list map a diff foo` will still fail (it was already failing), but I think here the problem is with the test itself.
Because the operators `map` and `diff` have the same precedence you can't remove the parens.
`list map a diff foo` is the same as `list.map(a).diff(foo)`
`list map (a diff foo)` is the same as `list.map(a.diff(foo))`
So they are not equivalent expressions

**Comment by olafurpg** [comment]
@RCMartins nice job tracking down the problem! Your analysis sounds correct 👍

**Comment by hugo-vrijswijk** [comment]
@RCMartins thanks for the explanation! Very insightful. I've learned a lot about Scala syntax this week haha. The `list map a diff foo` was indeed incorrect (structure comparison also failed). The test cases and code should now be correct

**Comment by olafurpg** [comment]
@hugo-vrijswijk I can try to cut a new release in the coming week with the pretty-printer fixes. Are there other blocking issues you'd like to get in first?

**Comment by hugo-vrijswijk** [comment]
@olafurpg Not that I know of, but there could be 😉. But that'd be great!
