### PR TITLE
Do not escape symbols in multiline string interpolation

### LINKED ISSUE #2467: Parser does not handle backslash in raw strings
The usage of the following snippet in the code would lead to failures when trying to create SemanticDB. 
```
 val host = "foo"
 val share = "bar"
 raw"""\\$host\$share\"""
```
It looks like the last backlash is treated by the parser as an escape for char `"`, which then leads to treating the rest of the source files as an unclosed string. In the result, if we would try to define some other interpreted strings parser would fail to process them resulting in the compiler failure, here's a stack trace for my use case: 
```
2021.09.06 10:28:48 ERROR failed to generate semanticdb for ...scala/scala-native/javalib/src/main/scala/scala/scalanative/nio/fs/windows/WindowsPathParser.scala:
.../scala/scalanative/nio/fs/windows/WindowsPathParser.scala:138: error: unclosed multi-line string interpolation
          s"Illegal character `${segment.charAt(invalidCharIdx)}` in path",
                                                                ^
	at scala.meta.internal.tokenizers.Reporter.incompleteInputError(Reporter.scala:27)
	at scala.meta.internal.tokenizers.Reporter.incompleteInputError$(Reporter.scala:26)
	at scala.meta.internal.tokenizers.Reporter$$anon$1.incompleteInputError(Reporter.scala:33)
	at scala.meta.internal.tokenizers.Reporter.incompleteInputError(Reporter.scala:29)
	at scala.meta.internal.tokenizers.Reporter.incompleteInputError$(Reporter.scala:29)
	at scala.meta.internal.tokenizers.Reporter$$anon$1.incompleteInputError(Reporter.scala:33)
	at scala.meta.internal.tokenizers.LegacyScanner.getStringPart(LegacyScanner.scala:762)
	at scala.meta.internal.tokenizers.LegacyScanner.fetchStringPart(LegacyScanner.scala:788)
	at scala.meta.internal.tokenizers.LegacyScanner.fetchToken(LegacyScanner.scala:321)
	at scala.meta.internal.tokenizers.LegacyScanner.nextToken(LegacyScanner.scala:251)
	at scala.meta.internal.tokenizers.LegacyScanner.foreach(LegacyScanner.scala:1111)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.uncachedTokenize(ScalametaTokenizer.scala:157)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.$anonfun$tokenize$1(ScalametaTokenizer.scala:17)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:895)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.tokenize(ScalametaTokenizer.scala:17)
	at scala.meta.internal.tokenizers.ScalametaTokenizer$$anon$2.apply(ScalametaTokenizer.scala:336)
	at scala.meta.tokenizers.Api$XtensionTokenizeDialectInput.tokenize(Api.scala:25)
	at scala.meta.tokenizers.Api$XtensionTokenizeInputLike.tokenize(Api.scala:14)
	at scala.meta.internal.parsers.ScalametaParser.scannerTokens$lzycompute(ScalametaParser.scala:241)
	at scala.meta.internal.parsers.ScalametaParser.scannerTokens(ScalametaParser.scala:241)
	at scala.meta.internal.parsers.ScalametaParser.<init>(ScalametaParser.scala:155)
	at scala.meta.internal.parsers.ScalametaParser$$anon$263.apply(ScalametaParser.scala:5257)
	at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:25)
	at scala.meta.internal.semanticdb.scalac.ParseOps$XtensionCompilationUnitSource.toSource(ParseOps.scala:17)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument.toTextDocument(TextDocumentOps.scala:201)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument.toTextDocument(TextDocumentOps.scala:52)
	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.saveSemanticdbForCompilationUnit(SemanticdbPipeline.scala:60)
	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.apply(SemanticdbPipeline.scala:67)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:453)

```

### PR DESCRIPTION
**Pull request by dos65**
Fixes #2467.
Aligned with [implementation in compiler](https://github.com/lampepfl/dotty/blob/adefa482667f8a3bfed9951c522677b2418d9610/compiler/src/dotty/tools/dotc/parsing/Scanners.scala#L1141-L1148)

### CODE REVIEW

File: tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala [hunk 1]
```diff
@@ -1023,4 +1023,25 @@ class TokenizerSuite extends BaseTokenizerSuite {
...
+      Interpolation.SpliceEnd(),
+      Interpolation.Part("\\"),
+      Interpolation.SpliceStart(),
+      Ident("share"),
+      Interpolation.SpliceEnd(),
+      Interpolation.Part("\\"),
+      Interpolation.End(),
+      EOF()
+    ) =
+      ("raw\"\"\"\\$host\\$share\\\"\"\"").tokenize.get
```
Comment (kitbellew) [inline tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala:1044]: do we need to handle the non-multiline `raw` strings: `raw"a\nb"`

https://docs.scala-lang.org/overviews/core/string-interpolation.html#the-raw-interpolator

File: scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala [hunk 2]
```diff
@@ -695,10 +695,13 @@ class LegacyScanner(input: Input, dialect: Dialect) {
         setStrVal()
         token = STRINGLIT
       }
-    } else if (ch == '\\') {
-      nextRawChar()
+    } else if (ch == '\\' && !multiLine) {
       putChar(ch)
       nextRawChar()
+      if (ch == '"' || ch == '\\') {
```
Comment (kitbellew) [inline scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala:701]: the linked compiler code looks like this:
```
        if (ch == '"' || ch == '\\')
          putChar(ch)
          nextRawChar()
```

is it using significant indentation without `then`? or is `nextRawChar()` outside of the `if` block?

File: scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala [hunk 3]
```diff
@@ -695,10 +695,13 @@ class LegacyScanner(input: Input, dialect: Dialect) {
         setStrVal()
         token = STRINGLIT
       }
-    } else if (ch == '\\') {
-      nextRawChar()
+    } else if (ch == '\\' && !multiLine) {
```
Comment (kitbellew) [inline scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala:698]: what happens if `multiline = true`?

File: scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala (hunk 2 above)
Comment (dos65) [reply scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala:701]: yep - significant indentation without then

File: scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala (hunk 3 above)
Comment (dos65) [reply scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala:698]: The difference is that for `multiline = true` having `\` at the end of is allowed.
This affect only closing quotes handling: `\"""` and `\"`
```scala
raw"""ab\""" // ok
raw"ab\"     // error - unclosed string literal
```

File: tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala (hunk 1 above)
Comment (dos65) [reply tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala:1044]: this sample works well

**Review by tgodzik — APPROVED** [review]
LGTM!
