### PR TITLE
Fix #1119 (Type.Param with Name.Anonymous is not supported in Dotty)

### LINKED ISSUE #1119: Type.Param with Name.Anonymous is not supported in Dotty
```scala
trait F[_]
```

results in
```scala
-- [E039] Syntax Error: foo.scala:1:8 ------------------------------------------
1 |trait F[_]
  |        ^
  |        an identifier expected, but '_' found

Explanation
===========

If you necessarily want to use '_' as identifier, you may put it in backticks.

```

### PR DESCRIPTION
**Pull request by kpbochenek**
Fix "Type.Param with Name.Anonymous is not supported in Dotty"

### CODE REVIEW

File: scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala [hunk 1]
```diff
@@ -3800,7 +3831,11 @@ class ScalametaParser(input: Input, dialect: Dialect) { parser =>
 
   def enumSingleCaseDef(mods: List[Mod]): Defn.EnumCase = {
     val name = termName()
-    val tparams = typeParamClauseOpt(ownerIsType = true, ctxBoundsAllowed = true)
+    val tparams = typeParamClauseOpt(
+      ownerIsType = true,
+      ctxBoundsAllowed = true,
+      allowUnderscore = dialect.allowTypeParamUnderscore
```
Comment (tgodzik) [inline scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala:3837]: Why not have it in one place only? Why do we need to forward it through all the functions?

**Review by tgodzik — APPROVED** [review]
LGTM with just one small question. Thanks for yet another improvement!

File: scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala (hunk 1 above)
Comment (kpbochenek) [reply scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala:3837]: That's because it is not in all functions, even example in issue shows this:
`F[_]` <- should fail
`F[X[_]]` <- valid
and this function is called recursively.

Comment (tgodzik) [reply scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala:3837]: Ok, thanks for the explanation!
