### PR TITLE
fix #650 #685

### LINKED ISSUE #650: semanticdb is dumped at the directory where sbt is run
It looks like scalac instantiated by sbt has an incorrect path in `global.settings.d.value`, and that confuses scalahost (https://github.com/scalameta/scalameta/blob/f26801820116511945d867d83f2a3f3312d8bf44/scalahost/src/main/scala/scala/meta/internal/scalahost/ScalahostPipeline.scala#L29).

@dwijnand I'd appreciate your advice.

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

File: scalahost/src/main/scala/scala/meta/internal/scalahost/ScalahostPipeline.scala [hunk 1]
```diff
@@ -26,7 +26,9 @@ trait ScalahostPipeline { self: ScalahostPlugin =>
 
       override def run(): Unit = {
         super.run()
-        val databaseFile = new File(global.settings.d.value + "/semanticdb")
+        val outputDir =
+          global.settings.outputDirs.getSingleOutput.getOrElse(global.settings.d.value)
+        val databaseFile = new File(outputDir + "/semanticdb")
```
Comment (olafurpg) [inline scalahost/src/main/scala/scala/meta/internal/scalahost/ScalahostPipeline.scala]: `new File(outputDir + File.separator + "semanticdb")`?

Comment (xeno-by) [inline scalahost/src/main/scala/scala/meta/internal/scalahost/ScalahostPipeline.scala]: Good point.
