### PR TITLE
Handle constant classOf types.

### LINKED ISSUE #1306: Metacp does not support constant ExistentialType
While running metacp on akka I hit on the following error
```
error: can't convert jar:file:///Users/ollie/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.9/akka-actor_2.12-2.5.9.jar!/akka/dispatch/Mailboxes.class
java.lang.RuntimeException: unsupported const ExistentialType(TypeRefType(ThisType(akka.dispatch),akka.dispatch.RequiresMessageQueue,List(TypeRefType(NoPrefixType,TypeSymbol(_$4, owner=169, flags=100, info=135 ),List()))),List(TypeSymbol(_$4, owner=169, flags=100, info=135 )))
	at scala.sys.package$.error(package.scala:27)
	at scala.meta.internal.metacp.Main$.loop$2(Main.scala:269)
	at scala.meta.internal.metacp.Main$.loop$2(Main.scala:298)
	at scala.meta.internal.metacp.Main$.stpe(Main.scala:346)
	at scala.meta.internal.metacp.Main$.sinfo(Main.scala:83)
	at scala.meta.internal.metacp.Main$.$anonfun$process$4(Main.scala:41)
```

I expected metacp to handle ExistentialType constants. 

I suspect the original signature is from here https://github.com/akka/akka/blob/b3a27d1c9f7504a982327d7e885a36a5a2c8f7a2/akka-actor/src/main/scala/akka/dispatch/Mailboxes.scala#L77

### PR DESCRIPTION
**Pull request by olafurpg**
Scalac encoded `classOf[T]` singleton types as `ConstantType(Type)`.
This commit adds custom handling for this type in metacp and metac
encoding them instead their widened representation `Class[T]`.

Fixes #1306

### CODE REVIEW

File: semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala [hunk 1]
```diff
@@ -249,6 +249,13 @@ object Main {
         //   val spre = loop(pre)
         //   val smix = loop(gmix)
         //   Some(s.Type(tag = stag, superType = Some(s.SuperType(spre, smix))))
+        case ConstantType(underlying: Type) =>
+          loop(underlying).map { sarg =>
+            val stag = t.TYPE_REF
+            val ssym = "_root_.java.lang.Class#"
+            val sargs = sarg :: Nil
+            s.Type(tag = stag, typeRef = Some(s.TypeRef(None, ssym, sargs)))
+          }
```
Comment (xeno-by) [inline semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala]: The prefix must be non-empty here as per the updated spec, but I'll take care of that myself when working on implementing the spec.
