### PR TITLE
tokenizers.CharArrayReader: allow surrogate pairs

### LINKED ISSUE #3328: scala.meta.tokenizers.TokenizeException
```2023.09.06 09:41:44 ERROR issues while parsing: C:\Users\partens\AppData\Local\Coursier\cache\v1\https\packages.schroders.com\artifactory\maven\ai\dragonfly\slash_3\0.1\slash_3-0.1-sources.jar
scala.meta.tokenizers.TokenizeException: jar:file:///C:/Users/partens/AppData/Local/Coursier/cache/v1/https/packages.corp.com/artifactory/maven/ai/dragonfly/slash_3/0.1/slash_3-0.1-sources.jar!/ai/dragonfly/math/Constant.scala:25: error: illegal character '\ud835'
  val 𝜑: Double = 1.46557123187676802665 // Golden
```
I think there is enough in that snippet (import the artefact into scala-cli) to reproduce this. I can provide more info if requred.

### PR DESCRIPTION
**Pull request by kitbellew**
Fixes #3328.

### CODE REVIEW

File: tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala [hunk 1]
```diff
@@ -1170,7 +1170,7 @@ class TokenizerSuite extends BaseTokenizerSuite {
   test("#3328") {
     val code = "val \\uD835\\uDF11: Double"
     val res = dialects.Scala212(code).tokenize
-    assertEquals(res.toEither.left.get.message, "illegal character '\\ud835'")
```
Comment (tgodzik) [inline tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala:1173]: Could you compare the tokens explicitely so that we can easily see how it's tokenized?

**Review by tgodzik — APPROVED** [review]
Looks good, just one small comment

File: tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala (hunk 1 above)
Comment (kitbellew) [reply tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala:1173]: added another test case
