### PR TITLE
ScannerTokens: handle `yield` in scala2

### LINKED ISSUE #3224: parse error since 4.8.1
### `build.sbt`

```scala
libraryDependencies += "org.scalameta" %% "scalameta" % "4.8.1"

scalaVersion := "2.13.11"
```

### `Main.scala`

```scala
import scala.meta._

object Main {
  def main(args: Array[String]): Unit = {
    val src = Input.String(
"""
for {
  x2 <- x1
} yield x2
  .x3 {
    case x4
        if x5.x6
          .x7(x8) =>
        x9
  }
"""
)
    val p = implicitly[parsers.Parse[Stat]]

    println(p.apply(src, dialects.Scala213).get.structure)
  }
}
```

### result `sbt run`

```
[info] running Main 
[error] <input>:6: error: => expected but \n found
[error]     case x4
[error]            ^
[error] 	at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:16)
[error] 	at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:16)
[error] 	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:22)
[error] 	at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:17)
[error] 	at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:17)
[error] 	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:22)
[error] 	at scala.meta.internal.parsers.ScalametaParser.syntaxErrorExpected(ScalametaParser.scala:367)
[error] 	at scala.meta.internal.parsers.ScalametaParser.expect(ScalametaParser.scala:369)
[error] 	at scala.meta.internal.parsers.ScalametaParser.accept(ScalametaParser.scala:373)
[error] 	at scala.meta.internal.parsers.ScalametaParser.caseBody$1(ScalametaParser.scala:2450)
[error] 	at scala.meta.internal.parsers.ScalametaParser.caseClause(ScalametaParser.scala:2462)
[error] 	at scala.meta.internal.parsers.ScalametaParser.iter$4(ScalametaParser.scala:2493)
[error] 	at scala.meta.internal.parsers.ScalametaParser.caseClausesIfAny(ScalametaParser.scala:2500)
[error] 	at scala.meta.internal.parsers.ScalametaParser.caseClauses(ScalametaParser.scala:2476)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$blockExpr$2(ScalametaParser.scala:2428)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:300)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:346)
[error] 	at scala.meta.internal.parsers.ScalametaParser.blockExpr(ScalametaParser.scala:2427)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$scala$meta$internal$parsers$ScalametaParser$$getArgClause$1(ScalametaParser.scala:2382)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:300)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:346)
[error] 	at scala.meta.internal.parsers.ScalametaParser.scala$meta$internal$parsers$ScalametaParser$$getArgClause(ScalametaParser.scala:2380)
[error] 	at scala.meta.internal.parsers.ScalametaParser.simpleExprRest(ScalametaParser.scala:2288)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$simpleExpr0$3(ScalametaParser.scala:2208)
[error] 	at scala.util.Success.map(Try.scala:262)
[error] 	at scala.meta.internal.parsers.ScalametaParser.simpleExpr0(ScalametaParser.scala:2208)
[error] 	at scala.meta.internal.parsers.ScalametaParser.simpleExpr(ScalametaParser.scala:2158)
[error] 	at scala.meta.internal.parsers.ScalametaParser.prefixExpr(ScalametaParser.scala:2141)
[error] 	at scala.meta.internal.parsers.ScalametaParser.postfixExpr(ScalametaParser.scala:2026)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$expr$2(ScalametaParser.scala:1607)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPosOpt(ScalametaParser.scala:303)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPosOpt(ScalametaParser.scala:347)
[error] 	at scala.meta.internal.parsers.ScalametaParser.expr(ScalametaParser.scala:1512)
[error] 	at scala.meta.internal.parsers.ScalametaParser.expr(ScalametaParser.scala:1403)
[error] 	at scala.meta.internal.parsers.ScalametaParser.exprMaybeIndented(ScalametaParser.scala:1425)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$expr$2(ScalametaParser.scala:1591)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPosOpt(ScalametaParser.scala:303)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPosOpt(ScalametaParser.scala:347)
[error] 	at scala.meta.internal.parsers.ScalametaParser.expr(ScalametaParser.scala:1512)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$1.$anonfun$applyOrElse$2(ScalametaParser.scala:4301)
[error] 	at scala.meta.internal.parsers.ScalametaParser.stat(ScalametaParser.scala:4338)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$1.applyOrElse(ScalametaParser.scala:4301)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$1.applyOrElse(ScalametaParser.scala:4294)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:338)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:334)
[error] 	at scala.meta.internal.parsers.ScalametaParser.entrypointStat(ScalametaParser.scala:4331)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$parseStat$1(ScalametaParser.scala:61)
[error] 	at scala.meta.internal.parsers.ScalametaParser.parseRuleAfterBOF(ScalametaParser.scala:51)
[error] 	at scala.meta.internal.parsers.ScalametaParser.parseRule(ScalametaParser.scala:46)
[error] 	at scala.meta.internal.parsers.ScalametaParser.parseStat(ScalametaParser.scala:61)
[error] 	at scala.meta.parsers.Parse$.$anonfun$parseStat$1(Parse.scala:14)
[error] 	at scala.meta.parsers.Parse$$anon$1.apply(Parse.scala:36)
[error] 	at Main$.main(Main.scala:20)
[error] 	at Main.main(Main.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] stack trace is suppressed; run last Compile / run for the full output

```

### run with scalameta 4.8.0

```
Term.ForYield(List(Enumerator.Generator(Pat.Var(Term.Name("x2")), Term.Name("x1"))), Term.Apply(Term.Select(Term.Name("x2"), Term.Name("x3")), Term.ArgClause(List(Term.PartialFunction(List(Case(Pat.Var(Term.Name("x4")), Some(Term.Apply(Term.Select(Term.Select(Term.Name("x5"), Term.Name("x6")), Term.Name("x7")), Term.ArgClause(List(Term.Name("x8")), None))), Term.Name("x9"))))), None)))
```

### PR DESCRIPTION
**Pull request by kitbellew**
Also remove scala3 check for `do` and `then` as these keywords naturally imply scala3. Fixes #3224. Follow-up to #3221.

### CODE REVIEW

File: scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala [hunk 1]
```diff
@@ -534,7 +534,7 @@ final class ScannerTokens(val tokens: Tokens)(implicit dialect: Dialect) {
           case (_: RegionDelim) :: (_: RegionFor) :: _ => sepRegions
           case xs => RegionIf(next) :: xs
         })
-      case _: KwThen if dialect.allowSignificantIndentation =>
+      case _: KwThen =>
```
Comment (tgodzik) [inline scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala:537]: Why the change with `then` ? Could you add a test for that?

**Review by tgodzik — CHANGES_REQUESTED** [review]

File: scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala (hunk 1 above)
Comment (kitbellew) [reply scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala:537]: no test. i mentioned in the commit comment that `then` only exists in scala3, so the dialect check is probably redundant, just like with `do`.

**Review by tgodzik — APPROVED** [review]
