### PR TITLE
Restore macro plugins from old analyzer.

### LINKED ISSUE #1135: semanticdb-scalac silently disables scalamacros/paradise
Minimized repro https://github.com/olafurpg/inThisBuild/commit/56371fac9f2f24316c9002eb9d3a17274c62112f

Execute `sbt a/run`

```scala
[error] [E2] a/src/main/scala/a/A.scala
[error]      not enough arguments for method asJson: (implicit encoder: io.circe.Encoder[a.Bar])io.circe.Json.
[error]      Unspecified value parameter encoder.
[error]      L10:  println(Bar(13, "Qux").asJson)
[error]      L10:                         ^
[error] [E1] a/src/main/scala/a/A.scala
[error]      could not find implicit value for parameter encoder: io.circe.Encoder[a.Bar]
[error]      L10:  println(Bar(13, "Qux").asJson)
[error]      L10:                         ^
[error] a/src/main/scala/a/A.scala: L10 [E1], L10 [E2]
[error] (a/compile:compileIncremental) Compilation failed
```

Commenting out `addCompilerPlugin(semanticdb)` makes the program compile and run.

Originally reported by @ngbinh in https://gitter.im/scalacenter/scalafix?at=59e5e2d9b20c64242911e7d3

### PR DESCRIPTION
**Pull request by olafurpg**
semanticdb-scalac hijacks the typechecking analyzer to attach important
metadata to tree nodes during typechecking. Previously, the hijacked
version of the analyzer would discard the existing macroPlugins from the
old analyzer. This caused semanticdb-scalac to be incompatible with
other compiler plugins like scalamacros/paradise. This commit changes
the hijacking step to copy over the macro plugins from the old analyzer
into the new analyzer.

Fixes #1135. This patch has only been manually tested.

### CODE REVIEW

File: scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/HijackAnalyzer.scala [hunk 1]
```diff
@@ -2,17 +2,27 @@ package scala.meta.internal
...
+      macroPluginsGetter.invoke(global.analyzer).asInstanceOf[List[MacroPlugin]]
+    }
     val newAnalyzer = new { val global: self.global.type = self.global } with SemanticdbAnalyzer
     val analyzerField = classOf[NscGlobal].getDeclaredField("analyzer")
     analyzerField.setAccessible(true)
     analyzerField.set(global, newAnalyzer)
+    oldMacroPlugins.foreach { oldMacroPlugin =>
+      // Restore macroPlugins from old analyzer, see https://github.com/scalameta/scalameta/issues/1135
+      newAnalyzer.addMacroPlugin(oldMacroPlugin.asInstanceOf[newAnalyzer.MacroPlugin])
+    }
```
Comment (xeno-by) [inline scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/HijackAnalyzer.scala]: What do you think about copying analyzer plugins, too?

Comment (olafurpg) [reply scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/HijackAnalyzer.scala]: Good idea, done.
