### PR TITLE
ScalametaParser: allow named types within `types()`

### LINKED ISSUE #4007: Named tuples parser error on latest metals snapshot
Metals server version: `1.4.0+6-73dc6db8-SNAPSHOT` which already includes `Scalameta v4.11.0` that added support for named tuples.

Code:
```scala
val y = summon[Tuple2[Int, String] <:< (x: Int, y: String)]
```

Error:
```
`)` expected but `:` found
```

### PR DESCRIPTION
**Pull request by kitbellew**
Fixes #4007. Alternative to #4009.

### CODE REVIEW

File: scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala [hunk 1]
```diff
@@ -780,6 +781,26 @@ class ScalametaParser(input: Input)(implicit dialect: Dialect) {
...
+        val mods = fmods
+        val modPos = if (mods.isEmpty) startPos else mods.head.begIndex
+        val name = atPos(startPos)(Type.Name(t.value))
+        val tpe = maybeParamType(allowFunctionType)
+        Some(autoEndPos(modPos)(Type.TypedParam(name, tpe, mods)))
+      case _ => None
+    }
+
+    private def maybeNamedType(): Type = {
+      val ok = dialect.allowImprovedTypeClassesSyntax
```
Comment (tgodzik) [inline scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala:800]: That's not really related to the change. That's named tuples, but we didn't add a separate dialect for it.

Comment (kitbellew) [reply scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala:800]: didn't realize that. so named tuples are ok to be parsed for any dialect, correct? ok, and other than, what do you think about this alternative?
