### PR TITLE
Fix #496: Remove view bounds support in Dotty dialect

### LINKED ISSUE #496: Remove view bounds support in Dotty dialect
View bounds have been completely removed in Dotty. The Dotty parser still supports them, so a good idea would be to remove such support. The Dotty dialect should fail for something like:
```scala
def foo[T <% Whatever](t: T) = ???
```
  
Current implementation: https://github.com/scalameta/scalameta/blob/master/scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L2782

### PR DESCRIPTION
**Pull request by jonas**
References #269

### CODE REVIEW

File: scalameta/dialects/src/main/scala/scala/meta/dialects/package.scala [hunk 1]
```diff
@@ -78,6 +83,7 @@ package object dialects {
     def allowInline = false
     def allowSpliceUnderscore = Scala210.allowSpliceUnderscore
     def allowToplevelTerms = true
+    def allowViewBounds = true
```
Comment (olafurpg) [inline scalameta/dialects/src/main/scala/scala/meta/dialects/package.scala]: Please reference `Scala210.allowViewBounds` in all dialects where the setting is true.

Comment (jonas) [inline scalameta/dialects/src/main/scala/scala/meta/dialects/package.scala]: OK, missed that pattern. Made `Paradise211` reference `Scala211`.

**Comment by xeno-by** [comment]
LGTM
