### PR TITLE
Make metac index incremental.

### LINKED ISSUE #1528: semanticdb.semanticidx does not play nicely with incremental compilation
Steps to reproduce https://github.com/olafurpg/semanticdb-zinc/commit/60ac13efe7604c2177a3d4fc6523210fa3007615

We need to figure out how to make semantic.semanticidx handle incremental compilation.

### PR DESCRIPTION
**Pull request by olafurpg**
This commit fixes a bug in metac so that it plays nicely with
incremental compilation under zinc. We use bloop in the tests to
simplify the integration with zinc and reproduce the bug. This
setup provides a modestly rapid edit/test/debug workflow.

Notes:

- To make semanticdb.semanticidx incremental, we merge an existing index
  file if it exists with the index metadata that we are about to
  persist. Along the way, we prune outdated data that references
  non-existing URIs.
- Zinc depends on an outdated version of ScalaPB (v0.6), which we
  exclude in build.sbt in favor of the latest version of ScalaPB (v0.7).
  Fortunately, Zinc uses only ScalaPB APIs that are available in v0.7
- Zinc is only compiled against 2.12 so the incremental tests run only
  for 2.12.
- The incremental tests take ~10-15s to run so they're labeled as slow.
- Thanks to the new testing infrastructure, we're able to integration test
  that orphan SemanticDB files are indeed removed by metac.

Fixes #1528

### CODE REVIEW

File: scalameta/testkit/src/main/scala/scala/meta/testkit/StringFS.scala [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+    * Creates a temporary directory with a layout matching the markup in the string.
+    *
+    * Example syntax of the expected markup in the string:
+    * {{{
+    *   fromString("""
+    *   /build.sbt
+    *   lazy val core = project
+    *   /src/main/scala/core/Foo.scala
+    *   package core
+    *   object Foo.scala
```
Comment (xeno-by) [inline scalameta/testkit/src/main/scala/scala/meta/testkit/StringFS.scala]: Fancy!

Comment (olafurpg) [reply scalameta/testkit/src/main/scala/scala/meta/testkit/StringFS.scala]: I already use `StringFS` in scalafmt and scalafix for a long time, it's very helpful!
