### PR TITLE
Fix #468: Add support for single parameter quasiquote

### LINKED ISSUE #468: quasiquote are unable to get parameter list
It seems hard to get parameter list using quasiquote. See the code below:
```scala
@ import scala.meta._
@ val q"case class $name($list)" = q"case class A(a:Int)"
cmd21.sc:1: identifier expected but ) found
val q"case class $name($list)" = q"case class A(a:Int)"
                            ^
Compilation Failed
```

This code works well with the quasiquote in current scala
```scala
@ import scala.reflect.runtime.universe._
@ val q"case class $name($list)" = q"case class A(a:Int)" 
name: TypeName = A
list: ValDef = <caseaccessor> <paramaccessor> val a: Int = _
```

But if there are multiple parameters, neither works:
```scala
@ import scala.meta._
@ val q"case class $name($list)" = q"case class A(a:Int,b:String)" 
cmd21.sc:1: identifier expected but ) found
val q"case class $name($list)" = q"case class A(a:Int,b:String)"
                            ^
Compilation Failed
```
```scala
@ import scala.reflect.runtime.universe._
@ val q"case class $name($list)" = q"case class A(a:Int,b:String)" 
scala.MatchError: case class A extends scala.Product with scala.Serializable {
  <caseaccessor> <paramaccessor> val a: Int = _;
  <caseaccessor> <paramaccessor> val b: String = _;
  def <init>(a: Int, b: String) = {
    super.<init>();
    ()
  }
} (of class scala.reflect.internal.Trees$ClassDef)
  $sess.cmd2$.<init>(cmd2.sc:1)
  $sess.cmd2$.<clinit>(cmd2.sc:-1)
```
I see a similar issue https://github.com/scalameta/scalameta/issues/458, but I'm not sure whether it is the same problem as described above.

### PR DESCRIPTION
**Pull request by jvican**
Quasiquotes can now pattern match on a single parameter in a primary constructor or function parameter list.

### CODE REVIEW

**Comment by jvican** [comment]
CI still failing because of git error.

**Comment by olafurpg** [comment]
👏  Excited to get this in ^_^

File: scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala [hunk 1]
```diff
@@ -2262,4 +2262,30 @@ class SuccessSuite extends FunSuite {
     val defnopt: Option[Stat] = Option(q"val x = 42")
     assert(q"..$defnopt".show[Structure] === "Term.Block(Seq(Defn.Val(Nil, Seq(Pat.Var.Term(Term.Name(\"x\"))), None, Lit(42))))")
   }
+
+  test("#468 - primary constructor") {
+    val q"case class A($arg)" = q"case class A(a: Int)"
```
Comment (xeno-by) [inline scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala]: I think that here and below `arg` should be renamed to `param`.

File: scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala [hunk 2]
```diff
@@ -2262,4 +2262,30 @@ class SuccessSuite extends FunSuite {
...
+    assert(arg.syntax === "a: Int")
+  }
+
+  test("#468 - function parameter list II") {
+    val q"def foo($arg, ..$args): Int = a" = q"def foo(a: Int, b: Int, c: Int): Int = a"
+    assert(arg.syntax === "a: Int")
+    assert(args.size === 2)
+    assert(args.head.syntax === "b: Int")
+    assert(args.tail.head.syntax === "c: Int")
+  }
```
Comment (xeno-by) [inline scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala]: Could you also add similar tests for type parameters?

**Comment by xeno-by** [comment]
See two suggested changes to the tests in comments. Otherwise LGTM.

File: scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala (hunk 1 above)
Comment (jvican) [inline scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala]: Agreed.

File: scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala (hunk 2 above)
Comment (jvican) [inline scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala]: Yes, I will add them soon.

**Comment by jvican** [comment]
Done.

**Comment by xeno-by** [comment]
LGTM
