### PR TITLE
ScalametaParser: detect new `given` syntax

### LINKED ISSUE #4047: `abstract givens cannot be anonymous` error with new Scala 3.6 given syntax
`build.sbt`

```scala
libraryDependencies += "org.scalameta" %% "scalameta" % "4.12.0"

scalaVersion := "2.13.15"
```

`Main.scala`

```scala
import scala.meta._

object Main {
  def main(args: Array[String]): Unit = {
    val src = Input.String("""given A[Int] {}""")
    val p = implicitly[parsers.Parse[Stat]]
    println(p.apply(src, dialects.Scala3).get.structure)
  }
}
```

```
[info] running Main 
[error] <input>:1: error: abstract givens cannot be anonymous
[error] given A[Int] {}
[error]       ^
[error] 	at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:16)
[error] 	at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:16)
[error] 	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:22)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$givenDecl$1(ScalametaParser.scala:3451)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoEndPos(ScalametaParser.scala:379)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoEndPos(ScalametaParser.scala:384)
[error] 	at scala.meta.internal.parsers.ScalametaParser.givenDecl(ScalametaParser.scala:3398)
[error] 	at scala.meta.internal.parsers.ScalametaParser.defOrDclOrSecondaryCtor(ScalametaParser.scala:3326)
[error] 	at scala.meta.internal.parsers.ScalametaParser.nonLocalDefOrDcl(ScalametaParser.scala:3309)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$1.applyOrElse(ScalametaParser.scala:4013)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$1.applyOrElse(ScalametaParser.scala:4008)
[error] 	at scala.meta.internal.parsers.ScalametaParser.entrypointStat(ScalametaParser.scala:4038)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$parseStat$1(ScalametaParser.scala:68)
[error] 	at scala.meta.internal.parsers.ScalametaParser.parseRuleAfterBOF(ScalametaParser.scala:58)
[error] 	at scala.meta.internal.parsers.ScalametaParser.parseRule(ScalametaParser.scala:53)
[error] 	at scala.meta.internal.parsers.ScalametaParser.parseStat(ScalametaParser.scala:68)
[error] 	at scala.meta.parsers.Parse$.$anonfun$parseStat$1(Parse.scala:15)
[error] 	at scala.meta.parsers.Parse$$anon$1.apply(Parse.scala:37)
[error] 	at Main$.main(Main.scala:7)
```


Scala 3.5.2

```
Welcome to Scala 3.5.2 (21.0.5, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                                                                                                        
scala> trait A[B]
// defined trait A
                                                                                                                                                                                                        
scala> given A[Int] with {}
// defined object given_A_Int
                                                                                                                                                                                                        
scala> given A[Int] {}
-- [E040] Syntax Error: --------------------------------------------------------
1 |given A[Int] {}
  |             ^
  |             'with' expected, but '{' found
```


Scala 3.6.2-RC2

```
Welcome to Scala 3.6.2-RC2 (21.0.5, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                                                                                                              
scala> trait A[B]
// defined trait A
                                                                                                                                                                                                              
scala> given A[Int] with {}
// defined object given_A_Int
                                                                                                                                                                                                              
scala> given A[Int] {}
// defined object given_A_Int
```

### note

maybe

- https://github.com/scala/scala3/pull/21668
- https://docs3.scala-lang.org/sips/sips/typeclasses-syntax.html

### PR DESCRIPTION
**Pull request by kitbellew**
The complexity largely arises from having to deal with both old and new. Fixes #4047.

### CODE REVIEW

**Comment by kitbellew** [comment]
@tgodzik should i split this up, to make it easier to review?

File: tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenSyntax36Suite.scala [hunk 1]
```diff
@@ -314,4 +314,553 @@ class GivenSyntax36Suite extends BaseDottySuite {
...
+  test("named, param clause first, coloneol") {
+    val code = """|given ord: (a: A) => Ord[A] => Ord[List[A]]:
+                  |  def foo = ???
+                  |""".stripMargin
+    val layout = "given ord: (a: A) => (Ord[A]) => Ord[List[A]] { def foo = ??? }"
+    val tree = Defn.Given(
+      Nil,
+      "ord",
+      Nil,
+      List(List(tparam("a", "A")), List(tparam("", papply("Ord", "A")))),
```
Comment (tgodzik) [inline tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenSyntax36Suite.scala:749]: Shouldn't we show this as a type lambda instead?

**Comment by tgodzik** [comment]
> @tgodzik should i split this up, to make it easier to review?

It should be fine, I just don't entirely understand the new syntax and need to spend some time on it. I will finish that today.

File: tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenSyntax36Suite.scala (hunk 1 above)
Comment (kitbellew) [reply tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenSyntax36Suite.scala:749]: a type lambda, i think, uses the `=>>` arrow. 

but in `given ord: (a: A) => Ord[A] => Ord[List[A]]`, you have a name (`ord`), two conditions (`(a: A)` and `Ord[A]`, i think they are interpreted as having their own `given` defined) and the type of the `given` expression (`Ord[List[A]]`).

none of the types above are lambdas or functions.

is your question why i didn't encode these conditions using a lambda, instead of type or term param clauses?

Comment (tgodzik) [reply tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenSyntax36Suite.scala:749]: Yeah, I am still thinking about whether that would even make sense to encode those as lambdas

Comment (kitbellew) [reply tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenSyntax36Suite.scala:749]: the existing trees used param clauses, so using anything else would require creating completely new trees; we can safely expand from one param clause to many but that's it. 

but the published ebnf uses, specifically, these four as GivenConditional:
- TypeParamClause (for [])
- TermParamClause (for () with param names)
- FunArgTypes (for () without param names)
- or an infix type but without refinements

so I've simply selected to use the first two and allow params not to have names (i e., anonymous names), which we already supported with `using` clauses anyway.

i thought it was the simplest, least dramatic change.

**Comment by tgodzik** [comment]
Should we do a release? I can start it.

**Comment by kitbellew** [comment]
let me check if i had anything small still pending, if not, we'll release
