### PR TITLE
[Scala3] While condition - accept multiply exprs in parens

### LINKED ISSUE #2380: scalameta parse error for valid Scala 3 code
**Describe the bug**

**To Reproduce**

```scala
object Test:

  var x = 1
  var y = 2
  while (x > 0) && (y > 0) do
    x -= 1
    y -= 1
```
This program gives a parse error on the `do`: 
```
    `;` expected but `do` found. (scalameta)
```

**Expected behavior**

It should parse. Interestingly, it does parse if `while` is replaced by `if` and `do` is replaced by `then`.

### PR DESCRIPTION
**Pull request by dos65**
Fixes #2380

### CODE REVIEW

File: tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala [hunk 1]
```diff
@@ -1103,6 +1103,26 @@ class ControlSyntaxSuite extends BaseDottySuite {
     )
   }
 
+  test("while-expr-do") {
+    val code =
+      """|  while (x > 0) && (y > 0) do
```
Comment (kitbellew) [inline tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala:1108]: should this also work:
```
  while (x > 0) && (y > 0) x += 1
```
also, is `do` allowed only in scala3?

Comment (dos65) [reply tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala:1108]: It shouldn't. It seems that the chained infix application works only if there is `do` keyword in the dotty parser.

Thanks for pointing at that. I will slightly rework that pr.

Comment (dos65) [reply tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala:1116]: Added checks on having `do`/`then` kw after complex expressions as it's works in scala3.

File: scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala [hunk 2]
```diff
@@ -2274,6 +2269,21 @@ class ScalametaParser(input: Input)(implicit dialect: Dialect) { parser =>
     }
   }
 
+  def condExprInParens[T <: Token: TokenInfo]: Term = {
+    if (dialect.allowSignificantIndentation) {
```
Comment (kitbellew) [inline scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala:2273]: i think this branch is not tested. you don't use scala 2 in any test cases?

**Review by kitbellew — APPROVED** [review]
implementation is good but one comment on test coverage

**Comment by tgodzik** [comment]
It seems to fail now on compiler/src/dotty/tools/dotc/core/Decorators.scala:171 in the dotty repo, you might need to add that test case too.

File: scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala (hunk 2 above)
Comment (dos65) [reply scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala:2273]: For scala2 this part branch isn't involved because the condition has to be inside braces.
There are tests for scala2 `if`/`while` in [TermSuite](https://github.com/scalameta/scalameta/blob/main/tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala).

**Review by tgodzik — APPROVED** [review]
LGTM!
