### PR TITLE
Run metacp on scala-library

### LINKED ISSUE #1302: Metacp crashes on NoSymbol
While testing metacp on the standard library I hit on many errors like

```
error: can't convert jar:file:///Users/ollie/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.jar!/scala/collection/GenTraversableOnce.class
java.lang.RuntimeException: unsupported symbol NoSymbol
	at scala.sys.package$.error(package.scala:27)
	at scala.meta.cli.metacp.Main$.ssymbol(Main.scala:90)
	at scala.meta.cli.metacp.Main$.ssymbol(Main.scala:88)
	at scala.meta.cli.metacp.Main$.sinfo(Main.scala:78)
	at scala.meta.cli.metacp.Main$.$anonfun$process$4(Main.scala:41)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.
```

### LINKED ISSUE #1303: Metacp crashes with IndexOutOfBoundsException
While running metacp  on scala-library I hit on multiple errors like this
```
error: can't convert jar:file:///Users/ollie/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.jar!/scala/collection/GenSet.class
java.lang.IndexOutOfBoundsException: 95
	at scala.collection.mutable.ArraySeq.apply(ArraySeq.scala:62)
	at scala.meta.cli.metacp.Main$.scala$meta$cli$metacp$Main$$skind(Main.scala:171)
	at scala.meta.cli.metacp.Main$.ssymbol(Main.scala:104)
	at scala.meta.cli.metacp.Main$.loop$2(Main.scala:226)
	at scala.meta.cli.metacp.Main$.$anonfun$stpe$1(Main.scala:227)
```

### PR DESCRIPTION
**Pull request by olafurpg**
This commit adds a test suite for running metacp on scala-library and
fixes the following two crashes

- Fix #1303 Fix IndexOutOfBounds
- Fix #1302 Handle NoSymbol

### CODE REVIEW

**Comment by olafurpg** [comment]
Metacp seems to have problems on Windows

```
[info]   java.net.URISyntaxException: Illegal character in opaque part at index 161: jar:file:///C:/Users/appveyor/AppData/Local/Coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.jar!/META-INF\MANIFEST.MF
```

https://ci.appveyor.com/project/olafurpg/scalameta/build/730#L3262

due to a bug in Fragment.

File: semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala [hunk 1]
```diff
@@ -69,6 +69,7 @@ object Main {
   }
 
   private def sinfo(sym: SymbolInfoSymbol): Option[s.SymbolInformation] = {
+    if (sym.parent.get == NoSymbol) return None
```
Comment (xeno-by) [inline semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala]: When can this happen?

File: semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala [hunk 2]
```diff
@@ -168,8 +169,15 @@ object Main {
...
         // are indistinguishable from each other.
-        val nameEntryType = sym.entry.scalaSig.table(sym.entry.index + 1)._1
-        val hasTermName = nameEntryType == 1
+        val hasTermName = {
+          val idx = sym.entry.index + 1
+          if (sym.entry.scalaSig.hasEntry(idx)) {
+            val nameEntryType = sym.entry.scalaSig.table(idx)._1
+            nameEntryType == 1
+          } else {
+            false
```
Comment (xeno-by) [inline semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala]: Do you happen to have a reproduction?

File: build.sbt [hunk 3]
```diff
@@ -436,6 +436,12 @@ lazy val tests = crossProject(JSPlatform, JVMPlatform)
     buildInfoPackage := "scala.meta.tests",
     libraryDependencies += "org.scalatest" %%% "scalatest" % "3.0.1" % "test"
   )
+  .jvmSettings(
+    libraryDependencies ++= List(
+      "io.get-coursier" %% "coursier" % coursier.util.Properties.version,
```
Comment (MasseGuillaume) [inline build.sbt]: `% Test`

File: semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala (hunk 2 above)
Comment (olafurpg) [reply semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala]: scala-library and scalameta jars reproduce it 100s of times, but I don't have a minimal reproduction. `scala.matching` was one case I remember. Once we have these tests + diff tests against metac we'll have plenty of opportunity to extract minimal reproductions. For now I think it's most important that new changes to metacp are tested against a large input to prevent further blatant crashes.

File: build.sbt (hunk 3 above)
Comment (olafurpg) [reply build.sbt]: This project contains only test sources

File: semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala (hunk 1 above)
Comment (olafurpg) [reply semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala]: This was the most frequent error, you can uncomment the line and run metacp suite to investigate.

**Comment by olafurpg** [comment]
YES!!!! 🎉 Tests pass now on windows.
