### PR TITLE
Finish remaining pieces from hackweek

### LINKED ISSUE #1067: Errors in Database.load should include input filename in the error message
I'm currently debugging an issue in how sbthost emits .semanticdb files during incremental compilation. The stack traces look like this

```
[info]   com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
[info]   at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:82)
[info]   at com.google.protobuf.CodedInputStream$ArrayDecoder.skipRawBytes(CodedInputStream.java:1200)
[info]   at com.google.protobuf.CodedInputStream$ArrayDecoder.skipField(CodedInputStream.java:575)
[info]   at lang.meta.internal.semanticdb.schema.Database.mergeFrom(Database.scala:45)
```

it would be nice if the message included the filename that was being loaded. That would help me inspect its contents and see why it's wrong.

### PR DESCRIPTION
**Pull request by olafurpg**
This PR supersedes  #1129. The biggest change is that semanticdbs are persisted immediately after typer, significantly reducing memory pressure for large projects. This change introduces a lot of complexity because some messages like deprecations are reported after typer. The solution in this PR is to append the messages reported after typer into the same .semanticdb file but as a separate m.Database and merge the two databases on m.Database.load. This is not an optimal solution, but it's the best we can do without compromising memory usage.

Fixes #1067

### CODE REVIEW

**Comment by olafurpg** [comment]
I kept the 2.11.11 sources of the analyzer, we can remove it in a couple of months once the community has had more time to upgrade to 2.11.12

File: scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/SemanticdbPipeline.scala [hunk 1]
```diff
@@ -72,10 +73,10 @@ trait SemanticdbPipeline extends DatabaseOps { self: SemanticdbPlugin =>
       override def apply(unit: g.CompilationUnit): Unit = {
         if (config.mode.isDisabled) return
         try {
-          unit.body.attachments.get[m.Document].foreach { mattrs =>
-            unit.body.removeAttachment[m.Document]
-            val messages = if (config.messages.saveMessages) unit.reportedMessages else Nil
-            val mminidb = m.Database(List(mattrs.copy(messages = messages)))
+          val messages = if (config.messages.saveMessages) unit.reportedMessages(Map.empty) else Nil
```
Comment (xeno-by) [inline scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/SemanticdbPipeline.scala]: Does this only fetch additional messages?

File: scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/SemanticdbPipeline.scala [hunk 2]
```diff
@@ -72,10 +73,10 @@ trait SemanticdbPipeline extends DatabaseOps { self: SemanticdbPlugin =>
...
+          if (messages.nonEmpty) {
+            val mminidb = m.Database(List(m.Document(unit.source.toInput, language, Nil, messages, Nil, Nil)))
+            // TODO(olafur) append here
```
Comment (xeno-by) [inline scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/SemanticdbPipeline.scala]: Does this todo mean that this is not appending but overwriting currently?

File: langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala [hunk 3]
```diff
@@ -25,94 +30,128 @@ package object semanticdb {
...
+    private def sdocumentsMerged: Seq[s.Document] = {
+      def isOnlyMessages(sdocument: s.Document) =
+        sdocument.contents.isEmpty &&
+          sdocument.messages.nonEmpty &&
+          sdocument.names.isEmpty &&
+          sdocument.synthetics.isEmpty &&
+          sdocument.symbols.isEmpty
+      if (sdatabase.documents.length <= 1) {
+        // NOTE(olafur) the most common case is that there is only a single database
+        // per document so we short-circuit here if that's the case.
```
Comment (xeno-by) [inline langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala]: How about merging the databases if the input is the same? That'll be more general than hardcoding this very specific condition.

File: langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala [hunk 4]
```diff
@@ -201,4 +230,32 @@ package object semanticdb {
...
+      case d.Message(pos, dSeverity(severity), msg) =>
+        s.Message(Some(s.Position(pos.start, pos.end)),severity, msg)
+    }
+    def append(filename: AbsolutePath, sourceroot: AbsolutePath, targetroot: AbsolutePath): Unit = {
+      val relpath = v.SemanticdbPaths.fromScala(filename.toRelative(sourceroot))
+      val semanticdbpath = targetroot.resolve(relpath)
+      val out = new RandomAccessFile(semanticdbpath.toFile, "rw")
+      try {
+        out.setLength(out.length() - 1)
+        s.Database().writeTo(???)
```
Comment (xeno-by) [inline langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala]: Triple question mark?

File: langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/vfs/Database.scala [hunk 5]
```diff
@@ -20,16 +21,43 @@ final case class Database(entries: List[Entry]) {
   def toSchema: s.Database = {
     val sentries = entries.flatMap { ventry =>
       val sdb = s.Database.parseFrom(ventry.bytes)
-      sdb.documents
+      // returns true if this document contains only messages and nothing else.
+      // deprecation messages are reported in refchecks and get persisted
+      // as standalone documents that need to be merged with their typer-phase
+      // document during loading. It seems there's no way to merge the documents
+      // during compilation without introducing a lot of memory pressure.
+      def isOnlyMessages(sdocument: s.Document): Boolean =
```
Comment (xeno-by) [inline langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/vfs/Database.scala]: Why do we have to duplicate this logic wrt `sdocumentsMerged`?

File: scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/SemanticdbPipeline.scala [hunk 6]
```diff
@@ -62,22 +69,32 @@ trait SemanticdbPipeline extends DatabaseOps { self: SemanticdbPlugin =>
...
-  object PersistSemanticdbComponent extends PluginComponent {
+  object SemanticdbJvmComponent extends PluginComponent {
     val global: SemanticdbPipeline.this.global.type = SemanticdbPipeline.this.global
     val runsAfter = List("jvm")
     override val runsRightAfter = Some("jvm")
-    val phaseName = "semanticdb-persist"
-    override val description = "persist semanticdb files"
+    val phaseName = "semanticdb-jvm"
+    override val description =
+      "compute and persist semanticdb information after typer (most commonly messages)"
```
Comment (xeno-by) [inline scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/SemanticdbPipeline.scala]: `compute and persist additional semanticdb entries created after typer`

File: scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/ConfigOps.scala [hunk 7]
```diff
@@ -24,8 +24,8 @@ case class SemanticdbConfig(
       s"-P:${SemanticdbPlugin.name}:profiling:${profiling.name} " +
       s"-P:${SemanticdbPlugin.name}:include:${fileFilter.include} " +
       s"-P:${SemanticdbPlugin.name}:exclude:${fileFilter.exclude} "
-      s"-P:${SemanticdbPlugin.name}:messages:${messages.name} " +
-      s"-P:${SemanticdbPlugin.name}:synthetics:${synthetics.name} "
+  s"-P:${SemanticdbPlugin.name}:messages:${messages.name} " +
+    s"-P:${SemanticdbPlugin.name}:synthetics:${synthetics.name} "
```
Comment (xeno-by) [inline scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/ConfigOps.scala]: Forgotten plus?

File: scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/ReporterOps.scala [hunk 8]
```diff
@@ -1,11 +1,14 @@
...
 
+import scala.collection.mutable
 import scala.tools.nsc.reporters.StoreReporter
 import scala.reflect.internal.util.{Position => gPosition}
 
 trait ReporterOps { self: DatabaseOps =>
-
+  // Hack, keep track of how many messages we have returns for each path to avoid
+  // duplicate messages. The key is System.identityHashCode to keep memory usage low.
+  private val returnedMessagesByPath = mutable.LongMap.empty[Int]
```
Comment (xeno-by) [inline scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/ReporterOps.scala]: I think we can use `unit` as a key. Units stay in memory for the entire duration of the compilation pipeline.

File: scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/ParseOps.scala [hunk 9]
```diff
@@ -9,7 +9,9 @@ trait ParseOps { self: DatabaseOps =>
     def toSource: m.Source = {
       val dialect =
         m.Dialect.standards.getOrElse(language, sys.error(s"unsupported dialect $language"))
-      unit.cache.getOrElse("source", dialect(unit.source.toInput).parse[m.Source].get)
+      // TODO(olafur) remove
+      // TODO(olafur) upgrade to 2.11.12
```
Comment (xeno-by) [inline scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/ParseOps.scala]: What do these todos mean?

File: langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala (hunk 3 above)
Comment (olafurpg) [reply langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala]: This method is a relic of a failed attempt, I've removed it.

> if the input is the same

Message-only documents have no .contents, and s.Database has no input.

File: langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala (hunk 4 above)
Comment (olafurpg) [reply langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala]: Removed, relic of failed attempt.

File: langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala [hunk 10]
```diff
@@ -201,4 +230,32 @@ package object semanticdb {
...
+        out.write(s.Database(s.Document(messages = toSchema) :: Nil).toByteArray)
+      } finally out.close()
+    }
+  }
+
+  private object dSeverity {
```
Comment (olafurpg) [inline langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala]: Moved this back to original location.

File: langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/vfs/Database.scala (hunk 5 above)
Comment (olafurpg) [reply langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/vfs/Database.scala]: I've consolidated the logic under the extension method `s.Database.mergeMessageOnlyDocuments: s.Database`.

File: scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/SemanticdbPipeline.scala (hunk 6 above)
Comment (olafurpg) [reply scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/SemanticdbPipeline.scala]: Done.

File: scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/ParseOps.scala (hunk 9 above)
Comment (olafurpg) [reply scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/ParseOps.scala]: Removed, I wrote those down during our call and committed them for some reason 😅

File: scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/ReporterOps.scala (hunk 8 above)
Comment (olafurpg) [reply scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/ReporterOps.scala]: Done.

File: scalameta/semanticdb-integration/src/main/scala/example/Exclude.scala [hunk 11]
```diff
@@ -0,0 +1,4 @@
+package exclude
+
+// This class should not be excluded by semanticdb.
```
Comment (xeno-by) [inline scalameta/semanticdb-integration/src/main/scala/example/Exclude.scala]: Should or should not? The build configuration says `s"-P:semanticdb:exclude:Exclude.scala",`

File: langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala (hunk 3 above)
Comment (xeno-by) [reply langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala]: But it does have an input, doesn't it? `input = m.Input.File(unit.source.file.file)`. Can we use this to correlate documents?

File: scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/ConfigOps.scala [hunk 12]
```diff
@@ -4,52 +4,82 @@ package semanticdb
...
   def syntax: String =
     s"-P:${SemanticdbPlugin.name}:sourceroot:$sourceroot " +
-      s"-P:${SemanticdbPlugin.name}:mode:$mode" +
-      s"-P:${SemanticdbPlugin.name}:failures:${failures.name} "
+      s"-P:${SemanticdbPlugin.name}:mode:${mode.name}" +
+      s"-P:${SemanticdbPlugin.name}:failures:${failures.name} " +
+      s"-P:${SemanticdbPlugin.name}:denotations:${denotations.name} " +
+      s"-P:${SemanticdbPlugin.name}:profiling:${profiling.name} " +
+      s"-P:${SemanticdbPlugin.name}:include:${fileFilter.include} " +
+      s"-P:${SemanticdbPlugin.name}:exclude:${fileFilter.exclude} "
```
Comment (xeno-by) [inline scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/ConfigOps.scala]: Still missing a plus here.

File: langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala (hunk 3 above)
Comment (xeno-by) [reply langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala]: If we don't have time to do this right now, let's merge but at least open an issue to make sure we follow through next time. This is some technical debt that we're taking on.

Comment (olafurpg) [reply langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala]: We don't have a source root so `m.Input.File()` won't work unless `sys.props("user.dir")` coincidentally matches --sourceroot. I think a step in the right direction to make this less hacky is https://github.com/scalameta/scalameta/issues/1151 we can persist the flavor of the persisted message in `s.Document`, one field could be to indicate that this is a message-only Document. Message-only are relevant outside of this use-case, I would use this also to implement something like https://github.com/olafurpg/sbt-messagehost

File: scalameta/semanticdb-integration/src/main/scala/example/Exclude.scala (hunk 11 above)
Comment (olafurpg) [reply scalameta/semanticdb-integration/src/main/scala/example/Exclude.scala]: Should be excluded, good catch!

File: scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/ConfigOps.scala (hunk 12 above)
Comment (olafurpg) [reply scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/ConfigOps.scala]: Whoa! Good eye 😉
