### PR TITLE
Scaladoc: fix label/desc for throws/version/since

### LINKED ISSUE #2398: Wrapping in scaladoc after @throws causes error
This template is a guideline, not a strict requirement.
- **Version**: 3.0.0-RC5
- **Integration**: VSCode or command line
- **Configuration**:
```
version = "3.0.0-RC5"
docstrings.style = AsteriskSpace
project.git = true
project.excludePaths = [
  "glob:**/scalalib/**"
]
# This creates less of a diff but is not default
# but is more aligned with Scala.js syntax.
newlines.beforeCurlyLambdaParams = multilineWithCaseOnly

# Keep control sites more streamlined
indent.ctrlSite = 4
danglingParentheses.ctrlSite = false

# default value is 10,000
# Message about NirGenExpr.scala goes away between 18k and 20k
runner.optimizer.maxVisitsPerToken = 20000
rewriteTokens = {
  "⇒": "=>"
  "→": "->"
  "←": "<-"
}

```

## Steps

Given code like this before and after:
```scala
-   *  @throws java.lang.InstantiationException (caused by a
-   *    `NoSuchMethodException`)
+   *  @throws
+   *    java.lang.InstantiationException (caused by a `NoSuchMethodException`)
    *    If this class does not have a public zero-argument constructor.
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Get errors when generating `scaladoc`.

```Scala
[error] /Users/eric/workspace/scala-native/test-interface-sbt-defs/src/main/scala/sbt/testing/OptionalThrowable.scala:27:3: Tag '@throws' must be followed by a symbol name
[error]   /** Returns the <code>Throwable</code> contained in this
[error]   ^
[error] /Users/eric/workspace/scala-native/test-interface-sbt-defs/src/main/scala/sbt/testing/Runner.scala:17:3: Tag '@throws' must be followed by a symbol name
[error]   /** Returns an array of tasks that when executed will run tests and suites
[error]   ^
[error] /Users/eric/workspace/scala-native/test-interface-sbt-defs/src/main/scala/sbt/testing/Framework.scala:18:3: Tag '@throws' must be followed by a symbol name
[error]   /** Initiates a run.
[error]   ^
[error] three errors found
model contains 323 documentable templates
[error] /Users/eric/workspace/scala-native/nativelib/src/main/scala/scala/scalanative/reflect/Reflect.scala:19:3: Tag '@throws' must be followed by a symbol name
[error]   /** Instantiates a new instance of this class using the zero-argument
[error]   ^
[error] one error found
```

## Expectation

Maybe not wrap `@throws` until after the exception type.

## Workaround

None known

## Notes

Current PR to Scala Native: https://github.com/scala-native/scala-native/pull/2315

### PR DESCRIPTION
**Pull request by kitbellew**
Fixes #2398.

### CODE REVIEW

File: scalameta/trees/shared/src/main/scala/scala/meta/internal/Scaladoc.scala [hunk 1]
```diff
@@ -215,7 +215,12 @@ object Scaladoc {
     case object Documentable extends Base("@documentable", hasDesc = true)
 
     /* Macros tags */
-    // @define <name> <definition>
+
+    /**
+     * Allows use of {{{label}}} in other Scaladoc comments within the same
+     * source file which will be expanded to the contents of {{{definition}}}.
+     */
+    case object Define extends Base("@define", hasLabel = true, hasDesc = true)
```
Comment (tgodzik) [inline scalameta/trees/shared/src/main/scala/scala/meta/internal/Scaladoc.scala:223]: Should we add a test for `@define` ?

Comment (kitbellew) [reply scalameta/trees/shared/src/main/scala/scala/meta/internal/Scaladoc.scala:223]: @tgodzik thanks, done.
